### PR TITLE
chore: gmd onboarding flow review

### PR DESCRIPTION
**Pull request by igormq**
Some points: 

- The user account creation (salt id) is done alongside with the person creation (`POST /api/v1/people`)
- The authoriser document upload occurs after all is done, am I right @rafaeldepaula and @andrelip? Should we cover it now?
- The merchant sign-up to acquiring gateway is also triggered by the onboarding ui
- Regarding the bank account, store bank account takes precedence over the company bank account
- All the calls are being done at the same time by the onboarding ui. there is no a step between sign-up and subscriptions, for example.
- Acquiring subscription @rafaeldepaula
  - field agent selects the fee type (blended MVP case) and the fee percentage
- Terminal registration @rafaeldepaula
  - field agent selects the number of terminals (1 MVP case) and input the serial number
- It would be nice if you guys have the figma flow for the ui @rafaeldepaula

### CODE REVIEW

**Comment by filipeblacksmith** [comment]
> All the calls are being done at the same time by the onboarding ui. there is no a step between sign-up and subscriptions, for example.

If these are paralleled, what happens if the KYC fails and the terminal is being subscribed? Or do you mean that the FA just does one request and sends all the data for KYC, acquiring, and terminal subscription and the Onboarding UI does all the calls afterwards? If this is the case, are these simultaneous (again the same question as before) or one after the other?

**Review by bbeildeck — COMMENTED** [review]
Missing the call from GOP to SaltID (creation of account), right? @igormq

**Comment by filipeblacksmith** [comment]
> The merchant sign-up to acquiring gateway is also triggered by the onboarding ui

Does this mean that we'll always have acquiring services subscribed by default when KYC'ing a new store? Is this what we want or what we have? Does it make sense to only do it when acquiring services are subscribed?

**Comment by igormq** [comment]
> > > All the calls are being done at the same time by the onboarding ui. there is no a step between sign-up and subscriptions, for example.
> > 
> > 
> > If these are paralleled, what happens if the KYC fails and the terminal is being subscribed? Or do you mean that the FA just does one request and sends all the data for KYC, acquiring, and terminal subscription and the Onboarding UI does all the calls afterwards? If this is the case, are these simultaneous (again the same question as before) or one after the other?
> 
> He meant to say sequentially one after the other, not in parallel

yes, it is sequentially. sorry, i wrote down it without thinking!

**Comment by igormq** [comment]
> > The merchant sign-up to acquiring gateway is also triggered by the onboarding ui
> 
> Does this mean that we'll always have acquiring services subscribed by default when KYC'ing a new store? Is this what we want or what we have? Does it make sense to only do it when acquiring services are subscribed?

it only happens when we want to subscribe to one of the acquiring services (terminal or acquiring)

**Comment by filipeblacksmith** [comment]
So if we do terminal subscription before acquiring, the GMD gets the partner subscription call? is this call just sent once by UI (meaning it checks beforehand) or does it send it always and GMD needs to ignore it if it's already subscribed as a partner? @igormq @rafaeldepaula @andrelip

(Also, please add the calls for the login part)

**Comment by andrelip** [comment]
> * The authoriser document upload occurs after all is done, am I right @rafaeldepaula and @andrelip? Should we cover it now?

If you consider the "onboarding" from the point of view of a bare minimum to test the interactions between products it's not part of the scope. As a true onboarding that complies with the legislation, this is something we need to do.

We have this feature and the GmD too, so I think it's okay to include it.

**Comment by andrelip** [comment]
> So if we do terminal subscription before acquiring, the GMD gets the partner subscription call? is this call just sent once by UI (meaning it checks beforehand) or does it send it always and GMD needs to ignore it if it's already subscribed as a partner? @igormq @rafaeldepaula @andrelip
> 
> (Also, please add the calls for the login part)

@igormq 
Since we are in this subject, are we able to receive feedback in the UI in case of success or failure?
For example, what will be the response if the field agent types an invalid serial number?

**Review by filipeblacksmith — APPROVED** [review]

**Pull request merged**
